### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by j-m-k** [ess-dmsc/conan-librdkafka#1]
Aloha!

Sorry to lay this at your doorstep, but we've been trying to adapt this package to build on Windows. We've had some trouble, and I was wondering if you were able\intending to support Windows builds via this packaging?

--J

**Comment by zjttoefs** [comment]
Good news: We do want to support Windows builds. @mattclarke will take a look.
Bad news: It's not a priority for us at the moment. 

Pull requests welcome ;)

**Comment by j-m-k** [comment]
I think we may have a PR for you pretty soon.  Thanks!

**Comment by jpscaduto** [comment]
Has there been any development/updates on this?

**Comment by mattclarke** [comment]
@jpscaduto @j-m-k 
This is now working on Windows. Clone the repo, switch to the branch and run `conan create. <user>/<channel> --settings librdkafka:build_type=Release --options librdkafka:shared=True`

**Comment by zjttoefs** [comment]
I assume this is working, since there was no update in a while. If there are remaining problems, please open a specific issue.
